openapi: 3.0.0
x-stoplight:
  id: 018fa124ecfc8
info:
  title: Wallet Service API
  version: 0.1.0
  description: |
    Api para exponer la funcionalidad del template.
  contact:
    name: Edilberto Martinez
    url: 'https://edilbertomd.github.io/portafoliolaboral/'
    email: edilberto_diaz14@hotmail.com
servers:
  - url: 'http://localhost:3000'
    description: Development/Test Server
  - url: 'http://localhost:4000'
    description: Production Server
paths:
  /health:
    get:
      summary: Ping echo for testing the services is up
      tags:
        - Health
      responses:
        '200':
          description: OK
      operationId: get-health
      description: Health check for the service
      security: []
  /ready:
    get:
      summary: Readiness check by executing base functionality
      tags:
        - Health
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/HTTP_Error_400'
        '401':
          $ref: '#/components/responses/HTTP_Error_400'
      operationId: GetReady
      description: Readiness check for the service
      security: []
  '/{version}/cliente':
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
          pattern: '^(?<major>[0-9]+).(?<minor>[0-9]+)$'
        description: Version of the API to use
    get:
      summary: Obtiene los clientes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteResult'
        '400':
          $ref: '#/components/responses/HTTP_Error_400'
        '401':
          $ref: '#/components/responses/HTTP_Error_400'
        '404':
          $ref: '#/components/responses/HTTP_Error_400'
      operationId: GetUser
      description: Obtiene el usuario
      security:
        - jwsToken: []
      tags:
        - Cliente
    post:
      summary: Crea un cliente
      operationId: PostCliente
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResult'
        '400':
          $ref: '#/components/responses/HTTP_Error_400'
        '401':
          $ref: '#/components/responses/HTTP_Error_400'
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Crea un cliente
      security:
        - jwsToken: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
        description: ''
      tags:
        - Cliente
  '/{version}/cliente/{idCliente}':
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
          pattern: '^(?<major>[0-9]+).(?<minor>[0-9]+)$'
        description: Version of the API to use
      - schema:
          type: string
        name: idCliente
        in: path
        required: true
        description: Id del cliente
    get:
      summary: Obtiene un cliente por id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResult'
        '400':
          $ref: '#/components/responses/HTTP_Error_400'
        '401':
          $ref: '#/components/responses/HTTP_Error_400'
        '404':
          $ref: '#/components/responses/HTTP_Error_400'
      operationId: GetUser
      description: Obtiene el usuario por id
      security:
        - jwsToken: []
      tags:
        - Cliente
    put:
      summary: Actualiza un cliente por id
      operationId: PutUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResult'
        '400':
          $ref: '#/components/responses/HTTP_Error_400'
        '401':
          $ref: '#/components/responses/HTTP_Error_400'
        '404':
          $ref: '#/components/responses/HTTP_Error_400'
      description: Actualiza un cliente por id
      security:
        - jwsToken: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteUpdateRequest'
      tags:
        - Cliente
    delete:
      summary: Elimina un cliente por id
      operationId: DeleteUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResult'
        '400':
          $ref: '#/components/responses/HTTP_Error_400'
        '401':
          $ref: '#/components/responses/HTTP_Error_400'
        '404':
          $ref: '#/components/responses/HTTP_Error_400'
      description: Elimina un cliente por id
      security:
        - jwsToken: []
      tags:
        - Cliente
components:
  schemas:
    ClienteResult:
      title: ClienteResult
      x-stoplight:
        id: gu55vk4o2l8gt
      type: object
      description: Estructura para consultar clientes
      properties:
        id:
          type: integer
          x-stoplight:
            id: 3of979vs8a9k9
        codigoPais:
          type: string
          minLength: 3
          maxLength: 3
          x-stoplight:
            id: neep14yhburn4
        telefono:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 9
          maxLength: 10
        nombre:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 100
        primerApellido:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 100
        segundoApellido:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 100
        fechaNacimiento:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 10
          format: date
          maxLength: 10
        genero:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 50
        correoElectronico:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 150
        tipoPersona:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 50
        curp:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 18
        rfc:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 13
        foto:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 500
        estado:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 500
        empresa:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 13
        guid:
          type: string
          description: Guid of the key-value configuration
          format: uuid
        creationTimestamp:
          type: string
          format: date-time
          description: Creation timestamp
        modificationTimestamp:
          type: string
          description: Modification timestamp
          format: date-time
        creationUser:
          type: string
          format: uuid
          description: Guid of the creation user
        modificationUser:
          type: string
          format: uuid
          description: Guid of the modification user
      required:
        - id
        - codigoPais
        - telefono
        - nombre
        - primerApellido
        - segundoApellido
        - fechaNacimiento
        - genero
        - correoElectronico
        - tipoPersona
        - curp
        - rfc
        - foto
        - estado
        - empresa
        - guid
        - creationTimestamp
        - modificationTimestamp
        - creationUser
        - modificationUser
    ClienteRequest:
      title: ClienteResult
      x-stoplight:
        id: zdjtcdgwyvde7
      type: object
      description: Estructura para consultar clientes
      properties:
        codigoPais:
          type: string
          minLength: 3
          maxLength: 3
          x-stoplight:
            id: neep14yhburn4
        telefono:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 9
          maxLength: 10
      required:
        - codigoPais
        - telefono
    ClienteUpdateRequest:
      title: ClienteResult
      x-stoplight:
        id: 0skzdo892adg6
      type: object
      description: Estructura para consultar clientes
      properties:
        id:
          type: integer
          x-stoplight:
            id: 3of979vs8a9k9
        nombre:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 100
        primerApellido:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 100
        segundoApellido:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 100
        fechaNacimiento:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 10
          format: date
          maxLength: 10
        genero:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 50
        correoElectronico:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 150
        estado:
          type: string
          x-stoplight:
            id: neep14yhburn4
          minLength: 1
          maxLength: 500
        modificationTimestamp:
          type: string
          description: Modification timestamp
          format: date-time
      required:
        - id
        - nombre
        - primerApellido
        - segundoApellido
        - fechaNacimiento
        - genero
        - correoElectronico
        - estado
        - modificationTimestamp
  securitySchemes:
    jwsToken:
      type: http
      scheme: bearer
    X-API-Key:
      name: X-API-Key
      type: apiKey
      in: header
  parameters:
    version:
      name: version
      in: path
      required: true
      schema:
        type: string
        pattern: '^(?<major>[0-9]+).(?<minor>[0-9]+)$'
      description: Version of the API to use
  responses:
    HTTP_Error_400:
      description: Response to client error satus code
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                description: List of errors
                items:
                  type: object
                  description: Standard error
                  properties:
                    errorCode:
                      type: string
                      description: Error key for internationalization purposes
                    type:
                      type: string
                      format: uri
                      description: Original URI
                      readOnly: true
                    title:
                      type: string
                      description: 'Error title, clear and concise'
                      readOnly: true
                    status:
                      type: integer
                      description: HTTP status for the specific error
                      format: int32
                      minimum: 0
                      exclusiveMinimum: true
                      readOnly: true
                    detail:
                      type: string
                      description: Full detail of the error
                      minLength: 15
                      readOnly: true
                    instance:
                      type: string
                      description: Specific instance where the error occurs without the base URI
                      minLength: 1
                      readOnly: true
                    extraAttributes:
                      type: object
                      description: Extra attributes
                      nullable: true
                      properties:
                        desciptionDynamicContents:
                          type: array
                          description: List of dynamic fields used in the detail of the error
                          nullable: true
                          items:
                            type: string
                        module:
                          type: string
                          description: Module that generated the error
                          nullable: true
                        serviceName:
                          type: string
                          description: Name of the service generating the error
                          nullable: true
                        serviceLocation:
                          type: string
                          description: Location of the service's instance
                          nullable: true
                  required:
                    - errorCode
                    - type
                    - title
                    - status
                    - detail
                    - instance
            required:
              - errors
          examples:
            Basic example:
              value:
                errors:
                  - errorCode: string
                    type: 'http://example.com'
                    title: string
                    status: 1
                    detail: stringstringstr
                    instance: string
                    extraAttributes:
                      desciptionDynamicContents:
                        - string
                      module: string
                      serviceName: string
                      serviceLocation: string
tags:
  - name: Cliente
  - name: Health
security:
  - jwsToken: []
  - X-API-Key: []
