/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using Wallet.RestAPI.Models;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using System.Threading.Tasks;
using Wallet.Funcionalidad.Models;

namespace Wallet.RestAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class AuthApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Login with credentials
        /// </summary>
        /// <remarks>Login with credentials</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="401">Response to client error satus code</response>
        [HttpPost]
        [Route(template: "/{version:apiVersion}/auth/login")]
        [ValidateModelState]
        [SwaggerOperation(summary: "Login")]
        [SwaggerResponse(statusCode: 200, type: typeof(Wallet.RestAPI.Models.AuthResult), description: "OK")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> LoginAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromBody] LoginRequest body);

        /// <summary>
        /// Refresh access token
        /// </summary>
        /// <remarks>Refresh access token</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        [HttpPost]
        [Route(template: "/{version:apiVersion}/auth/refresh")]
        [ValidateModelState]
        [SwaggerOperation(summary: "Refresh")]
        [SwaggerResponse(statusCode: 200, type: typeof(Wallet.RestAPI.Models.AuthResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> RefreshAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromBody] RefreshTokenRequest body);

        /// <summary>
        /// Revoke refresh token
        /// </summary>
        /// <remarks>Revoke refresh token</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="204">No Content</response>
        /// <response code="401">Response to client error satus code</response>
        [HttpPost]
        [Route(template: "/{version:apiVersion}/auth/revoke")]
        [ValidateModelState]
        [SwaggerOperation(summary: "Revoke")]
        [SwaggerResponse(statusCode: 204, description: "No Content")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> RevokeAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromBody] RevokeTokenRequest body);
    }
}
