/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using Wallet.RestAPI.Models;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using System.Threading.Tasks;

namespace Wallet.RestAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ClienteApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Elimina un cliente por id
        /// </summary>
        /// <remarks>Elimina un cliente por id</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idCliente">Id del cliente</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpDelete]
        [Route(template: "/{version:apiVersion}/cliente/{idCliente}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "DeleteCliente")]
        [SwaggerResponse(statusCode: 200, type: typeof(ClienteResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> DeleteClienteAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idCliente);

        /// <summary>
        /// Obtiene un cliente por id
        /// </summary>
        /// <remarks>Obtiene un cliente por id</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idCliente">Id del cliente</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route(template: "/{version:apiVersion}/cliente/{idCliente}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "GetCliente")]
        [SwaggerResponse(statusCode: 200, type: typeof(ClienteResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetClienteAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idCliente);

        /// <summary>
        /// Obtiene los clientes
        /// </summary>
        /// <remarks>Obtiene todos los clientes</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route(template: "/{version:apiVersion}/cliente")]
        [ValidateModelState]
        [SwaggerOperation(summary: "GetClientes")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ClienteResult>), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetClientesAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version);

        /// <summary>
        /// Crea un cliente
        /// </summary>
        /// <remarks>Crea un cliente</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        /// <response code="500">Internal Server Error</response>
        [HttpPost]
        [Route(template: "/{version:apiVersion}/cliente")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PostCliente")]
        [SwaggerResponse(statusCode: 201, type: typeof(ClienteResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PostClienteAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromBody] ClienteRequest body);


        /// <summary>
        /// Activa un cliente por id
        /// </summary>
        /// <remarks>Activa un cliente por id</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idCliente">Id del cliente</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route(template: "/{version:apiVersion}/cliente/{idCliente}/activar")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PutActivarCliente")]
        [SwaggerResponse(statusCode: 200, type: typeof(ClienteResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutActivarClienteAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idCliente);

        /// <summary>
        /// Actualiza un cliente por id
        /// </summary>
        /// <remarks>Actualiza un cliente por id</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idCliente">Id del cliente</param>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route(template: "/{version:apiVersion}/cliente/{idCliente}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PutCliente")]
        [SwaggerResponse(statusCode: 200, type: typeof(ClienteResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutClienteAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idCliente, [FromBody] ClienteUpdateRequest body);
    }
}
