/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using Wallet.RestAPI.Models;
using Wallet.RestAPI.Attributes;
using System.Threading.Tasks;

namespace Wallet.RestAPI.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class DispositivoMovilAutorizadoApiControllerBase : ControllerBase
    {
        /// <summary>
        /// Obtiene el dispositivo movil autroizado
        /// </summary>
        /// <remarks>Obtiene el dispositivo movil autorizado para entrar a la app</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idCliente">Id del cliente</param>
        /// <param name="idDispositivo">id del dispositivo</param>
        /// <param name="token">token autorizacion del dispositivo</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route("/{version:apiVersion}/dispositivoMovilAutorizado/{idCliente}")]
        [ValidateModelState]
        [SwaggerOperation("GetDispositivoMovilAutorizado")]
        [SwaggerResponse(statusCode: 200, type: typeof(bool?), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetDispositivoMovilAutorizadoAsync([FromRoute][Required][RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version, [FromRoute][Required] int? idCliente, [FromQuery] string idDispositivo, [FromQuery] string token);
        /// <summary>
        /// Guarda dispositivo movil autorizado
        /// </summary>
        /// <remarks>Gaurda dispositivo moveil autorizado del cliente</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idCliente">Id del cliente</param>
        /// <param name="body"></param>
        /// <response code="201">Created</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPost]
        [Route("/{version:apiVersion}/dispositivoMovilAutorizado/{idCliente}")]
        [ValidateModelState]
        [SwaggerOperation("PostDispositivoMovilAutorizado")]
        [SwaggerResponse(statusCode: 201, type: typeof(DispositivoMovilAutorizadoResult), description: "Created")]
        public abstract Task<IActionResult> PostDispositivoMovilAutorizadoAsync([FromRoute][Required][RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version, [FromRoute][Required] int idCliente, [FromBody] DispositivoMovilAutorizadoRequest body);
    }
}
