/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using Wallet.RestAPI.Models;

namespace Wallet.RestAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class EstadoApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Obtiene todos los estadosde la republica mexicana
        /// </summary>
        /// <remarks>Obtiene todos los estados de la republica mexicana</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route("/{version:apiVersion}/estado")]
        [ValidateModelState]
        [SwaggerOperation("GetEstados")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<EstadoResult>), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetEstadosAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version);

        /// <summary>
        /// Guarda un estado de mexico
        /// </summary>
        /// <remarks>Gaurda un estado de mexico</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPost]
        [Route("/{version:apiVersion}/estado")]
        [ValidateModelState]
        [SwaggerOperation("PostEstado")]
        [SwaggerResponse(statusCode: 201, type: typeof(EstadoResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PostEstadoAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromBody] EstadoRequest body);

        /// <summary>
        /// Actualiza un estado de mexico
        /// </summary>
        /// <remarks>Actualiza un estado de mexico</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idEstado">Id del estado</param>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route("/{version:apiVersion}/estado/{idEstado}")]
        [ValidateModelState]
        [SwaggerOperation("PutEstado")]
        [SwaggerResponse(statusCode: 200, type: typeof(EstadoResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutEstadoAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromRoute] [Required] int? idEstado, [FromBody] EstadoUpdateRequest body);
    }
}
