/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using Wallet.RestAPI.Models;

namespace Wallet.RestAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class KeyValueConfigApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Obtiene todas las configuraciones
        /// </summary>
        /// <remarks>Obtiene todas las configuraciones key-value</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        [HttpGet]
        [Route("/{version:apiVersion}/configurations")]
        [ValidateModelState]
        [SwaggerOperation("GetAllKeyValueConfigs")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<KeyValueConfigResult>), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetAllKeyValueConfigsAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version);

        /// <summary>
        /// Crea una nueva configuracion
        /// </summary>
        /// <param name="body"></param>
        /// <param name="version">Version of the API to use</param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        [HttpPost]
        [Route("/{version:apiVersion}/configurations")]
        [ValidateModelState]
        [SwaggerOperation("CreateKeyValueConfig")]
        [SwaggerResponse(statusCode: 201, type: typeof(KeyValueConfigResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> CreateKeyValueConfig([FromBody] KeyValueConfigRequest body,
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version);

        /// <summary>
        /// Elimina una configuracion por su clave
        /// </summary>
        /// <param name="key">Clave de la configuracion</param>
        /// <param name="version">Version of the API to use</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpDelete]
        [Route("/{version:apiVersion}/configurations/{key}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteKeyValueConfig")]
        [SwaggerResponse(statusCode: 200, type: typeof(KeyValueConfigResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> DeleteKeyValueConfig([FromRoute] [Required] string key,
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version);

        /// <summary>
        /// Obtiene una configuracion por su clave
        /// </summary>
        /// <param name="key">Clave de la configuracion</param>
        /// <param name="version">Version of the API to use</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route("/{version:apiVersion}/configurations/{key}")]
        [ValidateModelState]
        [SwaggerOperation("GetKeyValueConfigByKey")]
        [SwaggerResponse(statusCode: 200, type: typeof(KeyValueConfigResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetKeyValueConfigByKey([FromRoute] [Required] string key,
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version);

        /// <summary>
        /// Actualiza una configuracion existente
        /// </summary>
        /// <param name="body"></param>
        /// <param name="key">Clave de la configuracion</param>
        /// <param name="version">Version of the API to use</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route("/{version:apiVersion}/configurations/{key}")]
        [ValidateModelState]
        [SwaggerOperation("UpdateKeyValueConfig")]
        [SwaggerResponse(statusCode: 200, type: typeof(KeyValueConfigResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> UpdateKeyValueConfig([FromBody] KeyValueConfigUpdateRequest body,
            [FromRoute] [Required] string key,
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version);
    }
}
