/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using Wallet.RestAPI.Models;

namespace Wallet.RestAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ProveedorApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Elimina un proveedor de servicio
        /// </summary>
        /// <remarks>Elimina un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedor">Id del proveedor de servicio</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpDelete]
        [Route(template: "/{version:apiVersion}/proveedor/{idProveedor}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "DeleteProveedor")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> DeleteProveedorAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromRoute] [Required] int? idProveedor);

        /// <summary>
        /// Obtiene un proveedor de servicio por id
        /// </summary>
        /// <remarks>Obtiene un proveedor de servicio por id</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedor">Id del proveedor de servicio</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route(template: "/{version:apiVersion}/proveedor/{idProveedor}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "GetProveedor")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetProveedorAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromRoute] [Required] int? idProveedor);
        
        /// <summary>
        /// Obtiene todos los proveedores de servicio
        /// </summary>
        /// <remarks>Obtiene todos los proveedores de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="categoria">categoria del proveedor</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route(template: "/{version:apiVersion}/proveedor")]
        [ValidateModelState]
        [SwaggerOperation(summary: "GetProveedoresServicio")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ProveedorResult>), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetProveedoresServicioAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version, [FromQuery]string categoria);

        /// <summary>
        /// Guarda un proveedor de servicio
        /// </summary>
        /// <remarks>Guarda un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPost]
        [Route(template: "/{version:apiVersion}/proveedor")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PostProveedor")]
        [SwaggerResponse(statusCode: 201, type: typeof(ProveedorResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PostProveedorAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromBody] ProveedorRequest body);

        /// <summary>
        /// Activa un proveedor de servicio
        /// </summary>
        /// <remarks>Activa un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedor">Id del proveedor de servicio</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route(template: "/{version:apiVersion}/proveedor/{idProveedor}/activar")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PutActivarProveedor")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutActivarProveedorAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromRoute] [Required] int? idProveedor);

        /// <summary>
        /// Actualiza un proveedor de servicio
        /// </summary>
        /// <remarks>Actualiza un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedor">Id del proveedor de servicio</param>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route(template: "/{version:apiVersion}/proveedor/{idProveedor}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PutProveedor")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutProveedorAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")]
            string version,
            [FromRoute] [Required] int? idProveedor, [FromBody] ProveedorUpdateRequest body);
    }
}
