/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using Wallet.RestAPI.Models;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using System.Threading.Tasks;

namespace Wallet.RestAPI.Controllers
{
    /// <summary>
    /// Base controller for ProveedorServicio operations.
    /// </summary>
    [ApiController]
    public abstract class ProveedorServicioApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Elimina un proveedor de servicio
        /// </summary>
        /// <remarks>Elimina un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedorServicio">Id del proveedor de servicio</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpDelete]
        [Route(template: "/{version:apiVersion}/proveedorServicio/{idProveedorServicio}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "DeleteProveedorServicio")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorServicioResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> DeleteProveedorServicioAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idProveedorServicio);

        /// <summary>
        /// Obtiene un proveedor de servicio por id
        /// </summary>
        /// <remarks>Obtiene un proveedor de servicio por id</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedorServicio">Id del proveedor de servicio</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route(template: "/{version:apiVersion}/proveedorServicio/{idProveedorServicio}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "GetProveedorServicio")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorServicioResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetProveedorServicioAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idProveedorServicio);

        /// <summary>
        /// Obtiene todos los proveedores de servicio
        /// </summary>
        /// <remarks>Obtiene todos los proveedores de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route(template: "/{version:apiVersion}/proveedorServicio")]
        [ValidateModelState]
        [SwaggerOperation(summary: "GetProveedoresServicio")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ProveedorServicioResult>), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetProveedoresServicioAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version);

        /// <summary>
        /// Guarda un proveedor de servicio
        /// </summary>
        /// <remarks>Guarda un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPost]
        [Route(template: "/{version:apiVersion}/proveedorServicio")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PostProveedorServicio")]
        [SwaggerResponse(statusCode: 201, type: typeof(ProveedorServicioResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PostProveedorServicioAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromBody] ProveedorServicioRequest body);

        /// <summary>
        /// Activa un proveedor de servicio
        /// </summary>
        /// <remarks>Activa un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedorServicio">Id del proveedor de servicio</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route(template: "/{version:apiVersion}/proveedorServicio/{idProveedorServicio}/activar")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PutActivarProveedorServicio")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorServicioResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutActivarProveedorServicioAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idProveedorServicio);

        /// <summary>
        /// Actualiza un proveedor de servicio
        /// </summary>
        /// <remarks>Actualiza un proveedor de servicio</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idProveedorServicio">Id del proveedor de servicio</param>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route(template: "/{version:apiVersion}/proveedorServicio/{idProveedorServicio}")]
        [ValidateModelState]
        [SwaggerOperation(summary: "PutProveedorServicio")]
        [SwaggerResponse(statusCode: 200, type: typeof(ProveedorServicioResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutProveedorServicioAsync(
            [FromRoute] [Required] [RegularExpression(pattern: "^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int idProveedorServicio, [FromBody] ProveedorServicioRequest body);
    }
}
