/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using Wallet.RestAPI.Models;

namespace Wallet.RestAPI.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ServicioFavoritoApiControllerBase : ServiceBaseController
    {
        /// <summary>
        /// Elimina un servicio favorito
        /// </summary>
        /// <remarks>Elimina un servicio favorito</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idServicioFavorito">Id del servicio favorito</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpDelete]
        [Route("/{version:apiVersion}/servicioFavorito/{idServicioFavorito}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteServicioFavorito")]
        [SwaggerResponse(statusCode: 200, type: typeof(ServicioFavoritoResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> DeleteServicioFavoritoAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int? idServicioFavorito);

        /// <summary>
        /// Obtiene los servicios favoritos de un cliente
        /// </summary>
        /// <remarks>Obtiene los servicios favoritos de un cliente</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idCliente">Id del cliente</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpGet]
        [Route("/{version:apiVersion}/servicioFavorito/cliente/{idCliente}")]
        [ValidateModelState]
        [SwaggerOperation("GetServiciosFavoritos")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ServicioFavoritoResult>), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> GetServiciosFavoritosAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int? idCliente);

        /// <summary>
        /// Guarda un servicio favorito
        /// </summary>
        /// <remarks>Guarda un servicio favorito</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPost]
        [Route("/{version:apiVersion}/servicioFavorito")]
        [ValidateModelState]
        [SwaggerOperation("PostServicioFavorito")]
        [SwaggerResponse(statusCode: 201, type: typeof(ServicioFavoritoResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PostServicioFavoritoAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromBody] ServicioFavoritoRequest body);

        /// <summary>
        /// Actualiza un servicio favorito
        /// </summary>
        /// <remarks>Actualiza un servicio favorito</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idServicioFavorito">Id del servicio favorito</param>
        /// <param name="body"></param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route("/{version:apiVersion}/servicioFavorito/{idServicioFavorito}")]
        [ValidateModelState]
        [SwaggerOperation("PutServicioFavorito")]
        [SwaggerResponse(statusCode: 200, type: typeof(ServicioFavoritoResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400),
            description: "Response to client error satus code")]
        public abstract Task<IActionResult> PutServicioFavoritoAsync(
            [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
            [FromRoute] [Required] int? idServicioFavorito,
            [FromBody] ServicioFavoritoRequest body);
    }
}
