/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using Wallet.RestAPI.Models;

namespace Wallet.RestAPI.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class TarjetaEmitidaApiControllerBase : ServiceBaseController
    { 
        /// <summary>
        /// Actualiza la configuracion de una tarjeta
        /// </summary>
        /// <remarks>Actualiza la configuracion de una tarjeta</remarks>
        /// <param name="body"></param>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idTarjeta">Id de la tarjeta emitida</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Not Found</response>
        [HttpPut]
        [Route("/{version:apiVersion}/tarjetasemitidas/{idTarjeta}/configuracion")]
        [ValidateModelState]
        [SwaggerOperation("ActualizarConfiguracionTarjeta")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        public abstract Task<IActionResult> ActualizarConfiguracionTarjetaAsync(
          [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
          [FromBody] ConfiguracionTarjetaRequest body,
          [FromRoute] [Required] int? idTarjeta);

        /// <summary>
        /// Cambia el estado de bloqueo de una tarjeta
        /// </summary>
        /// <remarks>Cambia el estado de bloqueo de una tarjeta</remarks>
        /// <param name="body"></param>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idTarjeta">Id de la tarjeta emitida</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route("/{version:apiVersion}/tarjetasemitidas/{idTarjeta}/bloqueo")]
        [ValidateModelState]
        [SwaggerOperation("CambiarBloqueoTarjeta")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        public abstract Task<IActionResult> CambiarBloqueoTarjetaAsync(
          [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
          [FromBody] CambioBloqueoRequest body,
          [FromRoute] [Required] int? idTarjeta);
    }
}
