/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Wallet.RestAPI.Attributes;
using Wallet.RestAPI.Controllers.Base;
using Wallet.RestAPI.Models;

namespace Wallet.RestAPI.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class TarjetaVinculadaApiControllerBase : ServiceBaseController
    { 
        /// <summary>
        /// Desvincula una tarjeta
        /// </summary>
        /// <remarks>Desvincula una tarjeta existente</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idTarjeta">Id tarjeta vinculada o emitida</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpDelete]
        [Route("/{version:apiVersion}/tarjetasVinculadas/{idTarjeta}")]
        [ValidateModelState]
        [SwaggerOperation("DesvincularTarjeta")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        public abstract Task<IActionResult> DesvincularTarjetaAsync(
          [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
          [FromRoute] [Required] string idTarjeta);
        
        /// <summary>
        /// Establece tarjeta como favorita
        /// </summary>
        /// <remarks>Establece una tarjeta vinculada como la favorita</remarks>
        /// <param name="body"></param>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idTarjeta">Id tarjeta vinculada o emitida</param>
        /// <response code="200">OK</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPut]
        [Route("/{version:apiVersion}/tarjetasVinculadas/{idTarjeta}/favorita")]
        [ValidateModelState]
        [SwaggerOperation("EstablecerTarjetaFavorita")]
        [SwaggerResponse(statusCode: 200, type: typeof(TarjetaVinculadaResult), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        public abstract Task<IActionResult> EstablecerTarjetaFavoritaAsync(
          [FromBody] SetFavoritaRequest body,
          [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
          [FromRoute] [Required] string idTarjeta);

        /// <summary>
        /// Vincula una nueva tarjeta a una wallet
        /// </summary>
        /// <remarks>Vincula una nueva tarjeta a una wallet</remarks>
        /// <param name="body"></param>
        /// <param name="version">Version of the API to use</param>
        /// <param name="idWallet">Id de la cuenta wallet</param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        /// <response code="404">Response to client error satus code</response>
        [HttpPost]
        [Route("/{version:apiVersion}/cuentaWallet/{idWallet}/tarjetasVinculadas")]
        [ValidateModelState]
        [SwaggerOperation("VincularTarjeta")]
        [SwaggerResponse(statusCode: 201, type: typeof(TarjetaVinculadaResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        [SwaggerResponse(statusCode: 404, type: typeof(InlineResponse400), description: "Response to client error satus code")]
        public abstract Task<IActionResult> VincularTarjetaAsync(
          [FromBody] VincularTarjetaRequest body,
          [FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version,
          [FromRoute] [Required] string idWallet);
    }
}
