/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para aceptar terminos
    /// </summary>
    [DataContract]
    public partial class AceptarTerminosRequest : IEquatable<AceptarTerminosRequest>
    {
        /// <summary>
        /// Gets or Sets IdUsuario
        /// </summary>
        [DataMember(Name = "idUsuario")]
        public int IdUsuario { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name = "version")]
        public string Version { get; set; }

        /// <summary>
        /// Gets or Sets AceptoTerminos
        /// </summary>
        [DataMember(Name = "aceptoTerminos")]
        public bool AceptoTerminos { get; set; }

        /// <summary>
        /// Gets or Sets AceptoPrivacidad
        /// </summary>
        [DataMember(Name = "aceptoPrivacidad")]
        public bool AceptoPrivacidad { get; set; }

        /// <summary>
        /// Gets or Sets AceptoPld
        /// </summary>
        [DataMember(Name = "aceptoPld")]
        public bool AceptoPld { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class AceptarTerminosRequest {\n");
            sb.Append(value: "  IdUsuario: ").Append(value: IdUsuario).Append(value: "\n");
            sb.Append(value: "  Version: ").Append(value: Version).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (AceptarTerminosRequest)obj);
        }

        /// <summary>
        /// Returns true if AceptarTerminosRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AceptarTerminosRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AceptarTerminosRequest other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return
                (
                    IdUsuario == other.IdUsuario ||
                    IdUsuario.Equals(other.IdUsuario)
                ) &&
                (
                    Version == other.Version ||
                    Version != null &&
                    Version.Equals(other.Version)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                hashCode = hashCode * 59 + IdUsuario.GetHashCode();
                if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(AceptarTerminosRequest left, AceptarTerminosRequest right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(AceptarTerminosRequest left, AceptarTerminosRequest right)
        {
            return !Equals(objA: left, objB: right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}
