/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para aceptar terminos
    /// </summary>
    [DataContract]
    public partial class AceptarTerminosRequest : IEquatable<AceptarTerminosRequest>
    {
        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [Required]
        [DataMember(Name = "version")]
        public string Version { get; set; }

        /// <summary>
        /// Gets or Sets AceptoTerminos
        /// </summary>
        [Required]
        [DataMember(Name = "aceptoTerminos")]
        public bool? AceptoTerminos { get; set; }

        /// <summary>
        /// Gets or Sets AceptoPrivacidad
        /// </summary>
        [Required]
        [DataMember(Name = "aceptoPrivacidad")]
        public bool? AceptoPrivacidad { get; set; }

        /// <summary>
        /// Gets or Sets AceptoPld
        /// </summary>
        [Required]
        [DataMember(Name = "aceptoPld")]
        public bool? AceptoPld { get; set; }

        /// <summary>
        /// Gets or Sets ConcurrencyToken
        /// </summary>
        [DataMember(Name = "concurrencyToken")]
        public byte[] ConcurrencyToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AceptarTerminosRequest {\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  AceptoTerminos: ").Append(AceptoTerminos).Append("\n");
            sb.Append("  AceptoPrivacidad: ").Append(AceptoPrivacidad).Append("\n");
            sb.Append("  AceptoPld: ").Append(AceptoPld).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AceptarTerminosRequest)obj);
        }

        /// <summary>
        /// Returns true if AceptarTerminosRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AceptarTerminosRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AceptarTerminosRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Version == other.Version ||
                    Version != null &&
                    Version.Equals(other.Version)
                ) &&
                (
                    AceptoTerminos == other.AceptoTerminos ||
                    AceptoTerminos != null &&
                    AceptoTerminos.Equals(other.AceptoTerminos)
                ) &&
                (
                    AceptoPrivacidad == other.AceptoPrivacidad ||
                    AceptoPrivacidad != null &&
                    AceptoPrivacidad.Equals(other.AceptoPrivacidad)
                ) &&
                (
                    AceptoPld == other.AceptoPld ||
                    AceptoPld != null &&
                    AceptoPld.Equals(other.AceptoPld)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                if (AceptoTerminos != null)
                    hashCode = hashCode * 59 + AceptoTerminos.GetHashCode();
                if (AceptoPrivacidad != null)
                    hashCode = hashCode * 59 + AceptoPrivacidad.GetHashCode();
                if (AceptoPld != null)
                    hashCode = hashCode * 59 + AceptoPld.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(AceptarTerminosRequest left, AceptarTerminosRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AceptarTerminosRequest left, AceptarTerminosRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}
