/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para confirmar 2FA (SMS o Email)
    /// </summary>
    [DataContract]
    public partial class ConfirmacionRequest : IEquatable<ConfirmacionRequest>
    {
        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name = "Tipo")]
        public Tipo2FAEnum Tipo { get; set; }

        /// <summary>
        /// Gets or Sets Codigo
        /// </summary>
        [DataMember(Name = "Codigo")]
        public string Codigo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class ConfirmacionRequest {\n");
            sb.Append(value: "class ConfirmacionRequest {\n");
            sb.Append(value: "  Tipo: ").Append(value: Tipo).Append(value: "\n");
            sb.Append(value: "  Codigo: ").Append(value: Codigo).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (ConfirmacionRequest)obj);
        }

        /// <summary>
        /// Returns true if ConfirmacionRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ConfirmacionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConfirmacionRequest other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return
                (
                    Tipo == other.Tipo ||
                    Tipo.Equals(other.Tipo)
                ) &&
                (
                    Codigo == other.Codigo ||
                    Codigo != null &&
                    Codigo.Equals(other.Codigo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                // Suitable nullity checks etc, of course :)
                hashCode = hashCode * 59 + Tipo.GetHashCode();
                if (Codigo != null)
                    hashCode = hashCode * 59 + Codigo.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(ConfirmacionRequest left, ConfirmacionRequest right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(ConfirmacionRequest left, ConfirmacionRequest right)
        {
            return !Equals(objA: left, objB: right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}
