/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ConsentimientoUsuarioResult : IEquatable<ConsentimientoUsuarioResult>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets IdUsuario
        /// </summary>
        [Required]
        [DataMember(Name = "idUsuario")]
        public int? IdUsuario { get; set; }

        /// <summary>
        /// Gets or Sets TipoDocumento
        /// </summary>
        [Required]
        [DataMember(Name = "tipoDocumento")]
        public string TipoDocumento { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [Required]
        [DataMember(Name = "version")]
        public string Version { get; set; }

        /// <summary>
        /// Gets or Sets FechaAceptacion
        /// </summary>
        [Required]
        [DataMember(Name = "fechaAceptacion")]
        public DateTime? FechaAceptacion { get; set; }


        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [Required]
        [DataMember(Name = "isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Token de concurrencia
        /// </summary>
        /// <value>Token de concurrencia</value>
        [DataMember(Name = "concurrencyToken")]
        public string ConcurrencyToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class ConsentimientoUsuarioResult {\n");
            sb.Append(value: "  Id: ").Append(value: Id).Append(value: "\n");
            sb.Append(value: "  IdUsuario: ").Append(value: IdUsuario).Append(value: "\n");
            sb.Append(value: "  TipoDocumento: ").Append(value: TipoDocumento).Append(value: "\n");
            sb.Append(value: "  Version: ").Append(value: Version).Append(value: "\n");
            sb.Append(value: "  FechaAceptacion: ").Append(value: FechaAceptacion).Append(value: "\n");

            sb.Append(value: "  IsActive: ").Append(value: IsActive).Append(value: "\n");
            sb.Append(value: "  ConcurrencyToken: ").Append(value: ConcurrencyToken).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (ConsentimientoUsuarioResult)obj);
        }

        /// <summary>
        /// Returns true if ConsentimientoUsuarioResult instances are equal
        /// </summary>
        /// <param name="other">Instance of ConsentimientoUsuarioResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConsentimientoUsuarioResult other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other: other.Id)
                ) &&
                (
                    IdUsuario == other.IdUsuario ||
                    IdUsuario != null &&
                    IdUsuario.Equals(other: other.IdUsuario)
                ) &&
                (
                    TipoDocumento == other.TipoDocumento ||
                    TipoDocumento != null &&
                    TipoDocumento.Equals(value: other.TipoDocumento)
                ) &&
                (
                    Version == other.Version ||
                    Version != null &&
                    Version.Equals(value: other.Version)
                ) &&
                (
                    FechaAceptacion == other.FechaAceptacion ||
                    FechaAceptacion != null &&
                    FechaAceptacion.Equals(other: other.FechaAceptacion)
                ) &&
                (
                    IsActive == other.IsActive ||
                    IsActive != null &&
                    IsActive.Equals(other: other.IsActive)
                ) &&
                (
                    ConcurrencyToken == other.ConcurrencyToken ||
                    ConcurrencyToken != null &&
                    ConcurrencyToken.Equals(value: other.ConcurrencyToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (IdUsuario != null)
                    hashCode = hashCode * 59 + IdUsuario.GetHashCode();
                if (TipoDocumento != null)
                    hashCode = hashCode * 59 + TipoDocumento.GetHashCode();
                if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                if (FechaAceptacion != null)
                    hashCode = hashCode * 59 + FechaAceptacion.GetHashCode();

                if (IsActive != null)
                    hashCode = hashCode * 59 + IsActive.GetHashCode();
                if (ConcurrencyToken != null)
                    hashCode = hashCode * 59 + ConcurrencyToken.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(ConsentimientoUsuarioResult left, ConsentimientoUsuarioResult right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(ConsentimientoUsuarioResult left, ConsentimientoUsuarioResult right)
        {
            return !Equals(objA: left, objB: right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}
