/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ConsentimientoUsuarioRequest : IEquatable<ConsentimientoUsuarioRequest>
    { 
        /// <summary>
        /// Gets or Sets TipoDocumento
        /// </summary>
        [Required]

        [DataMember(Name="tipoDocumento")]
        public TipoDocumentoConsentimientoEnum TipoDocumento { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [Required]

        [StringLength(maximumLength: 20, MinimumLength=1)]
        [DataMember(Name="version")]
        public string Version { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class ConsentimientoUsuarioRequest {\n");
            sb.Append(value: "  TipoDocumento: ").Append(value: TipoDocumento).Append(value: "\n");
            sb.Append(value: "  Version: ").Append(value: Version).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (ConsentimientoUsuarioRequest)obj);
        }

        /// <summary>
        /// Returns true if ConsentimientoUsuarioRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ConsentimientoUsuarioRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConsentimientoUsuarioRequest other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return 
                (
                    TipoDocumento == other.TipoDocumento ||
                    TipoDocumento != null &&
                    TipoDocumento.Equals(obj: other.TipoDocumento)
                ) && 
                (
                    Version == other.Version ||
                    Version != null &&
                    Version.Equals(value: other.Version)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TipoDocumento != null)
                    hashCode = hashCode * 59 + TipoDocumento.GetHashCode();
                    if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ConsentimientoUsuarioRequest left, ConsentimientoUsuarioRequest right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(ConsentimientoUsuarioRequest left, ConsentimientoUsuarioRequest right)
        {
            return !Equals(objA: left, objB: right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
