/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Request to create a new wallet
    /// </summary>
    [DataContract]
    public partial class CrearCuentaWalletRequest : IEquatable<CrearCuentaWalletRequest>
    {
        /// <summary>
        /// Gets or Sets IdCliente
        /// </summary>
        [Required]
        [DataMember(Name = "idCliente")]
        public int? IdCliente { get; set; }

        /// <summary>
        /// Gets or Sets Moneda
        /// </summary>
        [Required]
        [DataMember(Name = "moneda")]
        public string Moneda { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class CrearCuentaWalletRequest {\n");
            sb.Append(value: "  IdCliente: ").Append(value: IdCliente).Append(value: "\n");
            sb.Append(value: "  Moneda: ").Append(value: Moneda).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (CrearCuentaWalletRequest)obj);
        }

        /// <summary>
        /// Returns true if CrearCuentaWalletRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of CrearCuentaWalletRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CrearCuentaWalletRequest other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return
                (
                    IdCliente == other.IdCliente ||
                    IdCliente != null &&
                    IdCliente.Equals(other: other.IdCliente)
                ) &&
                (
                    Moneda == other.Moneda ||
                    Moneda != null &&
                    Moneda.Equals(value: other.Moneda)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (IdCliente != null)
                    hashCode = hashCode * 59 + IdCliente.GetHashCode();
                if (Moneda != null)
                    hashCode = hashCode * 59 + Moneda.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(CrearCuentaWalletRequest left, CrearCuentaWalletRequest right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(CrearCuentaWalletRequest left, CrearCuentaWalletRequest right)
        {
            return !Equals(objA: left, objB: right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}
