/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CuentaWalletResult : IEquatable<CuentaWalletResult>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]

        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets IdCliente
        /// </summary>
        [Required]

        [DataMember(Name="idCliente")]
        public int? IdCliente { get; set; }

        /// <summary>
        /// Gets or Sets SaldoActual
        /// </summary>
        [Required]

        [DataMember(Name="saldoActual")]
        public double? SaldoActual { get; set; }

        /// <summary>
        /// Gets or Sets CuentaCLABE
        /// </summary>
        [Required]

        [DataMember(Name="cuentaCLABE")]
        public string CuentaCLABE { get; set; }

        /// <summary>
        /// Gets or Sets Moneda
        /// </summary>
        [Required]

        [DataMember(Name="moneda")]
        public string Moneda { get; set; }

        /// <summary>
        /// Guid unico del registro
        /// </summary>
        /// <value>Guid unico del registro</value>
        [Required]

        [DataMember(Name="guid")]
        public Guid? Guid { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        /// <value>Creation timestamp</value>
        [Required]

        [DataMember(Name="creationTimestamp")]
        public DateTime? CreationTimestamp { get; set; }

        /// <summary>
        /// Modification timestamp
        /// </summary>
        /// <value>Modification timestamp</value>
        [Required]

        [DataMember(Name="modificationTimestamp")]
        public DateTime? ModificationTimestamp { get; set; }

        /// <summary>
        /// Guid of the creation user
        /// </summary>
        /// <value>Guid of the creation user</value>
        [Required]

        [DataMember(Name="creationUser")]
        public Guid? CreationUser { get; set; }

        /// <summary>
        /// Guid of the modification user
        /// </summary>
        /// <value>Guid of the modification user</value>
        [Required]

        [DataMember(Name="modificationUser")]
        public Guid? ModificationUser { get; set; }

        /// <summary>
        /// Guid of the modification user
        /// </summary>
        /// <value>Guid of the modification user</value>
        [Required]

        [DataMember(Name="isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Token de concurrencia
        /// </summary>
        /// <value>Token de concurrencia</value>
        [Required]

        [DataMember(Name="concurrencyToken")]
        public string ConcurrencyToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CuentaWalletResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IdCliente: ").Append(IdCliente).Append("\n");
            sb.Append("  SaldoActual: ").Append(SaldoActual).Append("\n");
            sb.Append("  CuentaCLABE: ").Append(CuentaCLABE).Append("\n");
            sb.Append("  Moneda: ").Append(Moneda).Append("\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  CreationTimestamp: ").Append(CreationTimestamp).Append("\n");
            sb.Append("  ModificationTimestamp: ").Append(ModificationTimestamp).Append("\n");
            sb.Append("  CreationUser: ").Append(CreationUser).Append("\n");
            sb.Append("  ModificationUser: ").Append(ModificationUser).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ConcurrencyToken: ").Append(ConcurrencyToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CuentaWalletResult)obj);
        }

        /// <summary>
        /// Returns true if CuentaWalletResult instances are equal
        /// </summary>
        /// <param name="other">Instance of CuentaWalletResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CuentaWalletResult other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    IdCliente == other.IdCliente ||
                    IdCliente != null &&
                    IdCliente.Equals(other.IdCliente)
                ) && 
                (
                    SaldoActual == other.SaldoActual ||
                    SaldoActual != null &&
                    SaldoActual.Equals(other.SaldoActual)
                ) && 
                (
                    CuentaCLABE == other.CuentaCLABE ||
                    CuentaCLABE != null &&
                    CuentaCLABE.Equals(other.CuentaCLABE)
                ) && 
                (
                    Moneda == other.Moneda ||
                    Moneda != null &&
                    Moneda.Equals(other.Moneda)
                ) && 
                (
                    Guid == other.Guid ||
                    Guid != null &&
                    Guid.Equals(other.Guid)
                ) && 
                (
                    CreationTimestamp == other.CreationTimestamp ||
                    CreationTimestamp != null &&
                    CreationTimestamp.Equals(other.CreationTimestamp)
                ) && 
                (
                    ModificationTimestamp == other.ModificationTimestamp ||
                    ModificationTimestamp != null &&
                    ModificationTimestamp.Equals(other.ModificationTimestamp)
                ) && 
                (
                    CreationUser == other.CreationUser ||
                    CreationUser != null &&
                    CreationUser.Equals(other.CreationUser)
                ) && 
                (
                    ModificationUser == other.ModificationUser ||
                    ModificationUser != null &&
                    ModificationUser.Equals(other.ModificationUser)
                ) && 
                (
                    IsActive == other.IsActive ||
                    IsActive != null &&
                    IsActive.Equals(other.IsActive)
                ) && 
                (
                    ConcurrencyToken == other.ConcurrencyToken ||
                    ConcurrencyToken != null &&
                    ConcurrencyToken.Equals(other.ConcurrencyToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (IdCliente != null)
                    hashCode = hashCode * 59 + IdCliente.GetHashCode();
                    if (SaldoActual != null)
                    hashCode = hashCode * 59 + SaldoActual.GetHashCode();
                    if (CuentaCLABE != null)
                    hashCode = hashCode * 59 + CuentaCLABE.GetHashCode();
                    if (Moneda != null)
                    hashCode = hashCode * 59 + Moneda.GetHashCode();
                    if (Guid != null)
                    hashCode = hashCode * 59 + Guid.GetHashCode();
                    if (CreationTimestamp != null)
                    hashCode = hashCode * 59 + CreationTimestamp.GetHashCode();
                    if (ModificationTimestamp != null)
                    hashCode = hashCode * 59 + ModificationTimestamp.GetHashCode();
                    if (CreationUser != null)
                    hashCode = hashCode * 59 + CreationUser.GetHashCode();
                    if (ModificationUser != null)
                    hashCode = hashCode * 59 + ModificationUser.GetHashCode();
                    if (IsActive != null)
                    hashCode = hashCode * 59 + IsActive.GetHashCode();
                    if (ConcurrencyToken != null)
                    hashCode = hashCode * 59 + ConcurrencyToken.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CuentaWalletResult left, CuentaWalletResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CuentaWalletResult left, CuentaWalletResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
