/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para actualizar los datos del cliente
    /// </summary>
    [DataContract]
    public partial class DatosClienteRequest : IEquatable<DatosClienteRequest>
    { 
        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets ApellidoPaterno
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="apellidoPaterno")]
        public string ApellidoPaterno { get; set; }

        /// <summary>
        /// Gets or Sets ApellidoMaterno
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="apellidoMaterno")]
        public string ApellidoMaterno { get; set; }

        /// <summary>
        /// Gets or Sets NombreEstado
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="nombreEstado")]
        public string NombreEstado { get; set; }

        /// <summary>
        /// Gets or Sets FechaNacimiento
        /// </summary>
        [Required]

        [DataMember(Name="fechaNacimiento")]
        public DateTime? FechaNacimiento { get; set; }

        /// <summary>
        /// Gets or Sets Genero
        /// </summary>
        [Required]

        [DataMember(Name="genero")]
        public int? Genero { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class DatosClienteRequest {\n");
            sb.Append(value: "  Nombre: ").Append(value: Nombre).Append(value: "\n");
            sb.Append(value: "  ApellidoPaterno: ").Append(value: ApellidoPaterno).Append(value: "\n");
            sb.Append(value: "  ApellidoMaterno: ").Append(value: ApellidoMaterno).Append(value: "\n");
            sb.Append(value: "  NombreEstado: ").Append(value: NombreEstado).Append(value: "\n");
            sb.Append(value: "  FechaNacimiento: ").Append(value: FechaNacimiento).Append(value: "\n");
            sb.Append(value: "  Genero: ").Append(value: Genero).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (DatosClienteRequest)obj);
        }

        /// <summary>
        /// Returns true if DatosClienteRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of DatosClienteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DatosClienteRequest other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return 
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(value: other.Nombre)
                ) && 
                (
                    ApellidoPaterno == other.ApellidoPaterno ||
                    ApellidoPaterno != null &&
                    ApellidoPaterno.Equals(value: other.ApellidoPaterno)
                ) && 
                (
                    ApellidoMaterno == other.ApellidoMaterno ||
                    ApellidoMaterno != null &&
                    ApellidoMaterno.Equals(value: other.ApellidoMaterno)
                ) && 
                (
                    NombreEstado == other.NombreEstado ||
                    NombreEstado != null &&
                    NombreEstado.Equals(value: other.NombreEstado)
                ) && 
                (
                    FechaNacimiento == other.FechaNacimiento ||
                    FechaNacimiento != null &&
                    FechaNacimiento.Equals(other: other.FechaNacimiento)
                ) && 
                (
                    Genero == other.Genero ||
                    Genero != null &&
                    Genero.Equals(other: other.Genero)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                    if (ApellidoPaterno != null)
                    hashCode = hashCode * 59 + ApellidoPaterno.GetHashCode();
                    if (ApellidoMaterno != null)
                    hashCode = hashCode * 59 + ApellidoMaterno.GetHashCode();
                    if (NombreEstado != null)
                    hashCode = hashCode * 59 + NombreEstado.GetHashCode();
                    if (FechaNacimiento != null)
                    hashCode = hashCode * 59 + FechaNacimiento.GetHashCode();
                    if (Genero != null)
                    hashCode = hashCode * 59 + Genero.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DatosClienteRequest left, DatosClienteRequest right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(DatosClienteRequest left, DatosClienteRequest right)
        {
            return !Equals(objA: left, objB: right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
