/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para consultar la direccion de cliente
    /// </summary>
    [DataContract]
    public partial class DireccionResult : IEquatable<DireccionResult>
    { 
        /// <summary>
        /// Gets or Sets CodigoPostal
        /// </summary>
        [Required]

        [StringLength(maximumLength: 5, MinimumLength=5)]
        [DataMember(Name="codigoPostal")]
        public string CodigoPostal { get; set; }

        /// <summary>
        /// Gets or Sets Pais
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="pais")]
        public string Pais { get; set; }

        /// <summary>
        /// Gets or Sets Estado
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="estado")]
        public string Estado { get; set; }

        /// <summary>
        /// Gets or Sets Municipio_
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="municipio ")]
        public string Municipio { get; set; }

        /// <summary>
        /// Gets or Sets Colonia
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="colonia")]
        public string Colonia { get; set; }

        /// <summary>
        /// Gets or Sets Calle
        /// </summary>
        [Required]

        [StringLength(maximumLength: 100, MinimumLength=1)]
        [DataMember(Name="calle")]
        public string Calle { get; set; }

        /// <summary>
        /// Gets or Sets NumeroExterior
        /// </summary>
        [Required]

        [StringLength(maximumLength: 50, MinimumLength=1)]
        [DataMember(Name="numeroExterior")]
        public string NumeroExterior { get; set; }

        /// <summary>
        /// Gets or Sets NumeroInterior
        /// </summary>
        [Required]

        [StringLength(maximumLength: 6, MinimumLength=1)]
        [DataMember(Name="numeroInterior")]
        public string NumeroInterior { get; set; }

        /// <summary>
        /// Gets or Sets Referencia
        /// </summary>
        [Required]

        [StringLength(maximumLength: 250, MinimumLength=1)]
        [DataMember(Name="referencia")]
        public string Referencia { get; set; }

        /// <summary>
        /// Guid of the key-value configuration
        /// </summary>
        /// <value>Guid of the key-value configuration</value>
        [Required]

        [DataMember(Name="guid")]
        public Guid? Guid { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        /// <value>Creation timestamp</value>
        [Required]

        [DataMember(Name="creationTimestamp")]
        public DateTime? CreationTimestamp { get; set; }

        /// <summary>
        /// Modification timestamp
        /// </summary>
        /// <value>Modification timestamp</value>
        [Required]

        [DataMember(Name="modificationTimestamp")]
        public DateTime? ModificationTimestamp { get; set; }

        /// <summary>
        /// Guid of the creation user
        /// </summary>
        /// <value>Guid of the creation user</value>
        [Required]

        [DataMember(Name="creationUser")]
        public Guid? CreationUser { get; set; }

        /// <summary>
        /// Guid of the modification user
        /// </summary>
        /// <value>Guid of the modification user</value>
        [Required]

        [DataMember(Name="modificationUser")]
        public Guid? ModificationUser { get; set; }

        /// <summary>
        /// Guid of the modification user
        /// </summary>
        /// <value>Guid of the modification user</value>
        [Required]

        [DataMember(Name="isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class DireccionResult {\n");
            sb.Append(value: "  CodigoPostal: ").Append(value: CodigoPostal).Append(value: "\n");
            sb.Append(value: "  Pais: ").Append(value: Pais).Append(value: "\n");
            sb.Append(value: "  Estado: ").Append(value: Estado).Append(value: "\n");
            sb.Append(value: "  Municipio_: ").Append(value: Municipio).Append(value: "\n");
            sb.Append(value: "  Colonia: ").Append(value: Colonia).Append(value: "\n");
            sb.Append(value: "  Calle: ").Append(value: Calle).Append(value: "\n");
            sb.Append(value: "  NumeroExterior: ").Append(value: NumeroExterior).Append(value: "\n");
            sb.Append(value: "  NumeroInterior: ").Append(value: NumeroInterior).Append(value: "\n");
            sb.Append(value: "  Referencia: ").Append(value: Referencia).Append(value: "\n");
            sb.Append(value: "  Guid: ").Append(value: Guid).Append(value: "\n");
            sb.Append(value: "  CreationTimestamp: ").Append(value: CreationTimestamp).Append(value: "\n");
            sb.Append(value: "  ModificationTimestamp: ").Append(value: ModificationTimestamp).Append(value: "\n");
            sb.Append(value: "  CreationUser: ").Append(value: CreationUser).Append(value: "\n");
            sb.Append(value: "  ModificationUser: ").Append(value: ModificationUser).Append(value: "\n");
            sb.Append(value: "  IsActive: ").Append(value: IsActive).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (DireccionResult)obj);
        }

        /// <summary>
        /// Returns true if DireccionResult instances are equal
        /// </summary>
        /// <param name="other">Instance of DireccionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DireccionResult other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return 
                (
                    CodigoPostal == other.CodigoPostal ||
                    CodigoPostal != null &&
                    CodigoPostal.Equals(value: other.CodigoPostal)
                ) && 
                (
                    Pais == other.Pais ||
                    Pais != null &&
                    Pais.Equals(value: other.Pais)
                ) && 
                (
                    Estado == other.Estado ||
                    Estado != null &&
                    Estado.Equals(value: other.Estado)
                ) && 
                (
                    Municipio == other.Municipio ||
                    Municipio != null &&
                    Municipio.Equals(value: other.Municipio)
                ) && 
                (
                    Colonia == other.Colonia ||
                    Colonia != null &&
                    Colonia.Equals(value: other.Colonia)
                ) && 
                (
                    Calle == other.Calle ||
                    Calle != null &&
                    Calle.Equals(value: other.Calle)
                ) && 
                (
                    NumeroExterior == other.NumeroExterior ||
                    NumeroExterior != null &&
                    NumeroExterior.Equals(value: other.NumeroExterior)
                ) && 
                (
                    NumeroInterior == other.NumeroInterior ||
                    NumeroInterior != null &&
                    NumeroInterior.Equals(value: other.NumeroInterior)
                ) && 
                (
                    Referencia == other.Referencia ||
                    Referencia != null &&
                    Referencia.Equals(value: other.Referencia)
                ) && 
                (
                    Guid == other.Guid ||
                    Guid != null &&
                    Guid.Equals(other: other.Guid)
                ) && 
                (
                    CreationTimestamp == other.CreationTimestamp ||
                    CreationTimestamp != null &&
                    CreationTimestamp.Equals(other: other.CreationTimestamp)
                ) && 
                (
                    ModificationTimestamp == other.ModificationTimestamp ||
                    ModificationTimestamp != null &&
                    ModificationTimestamp.Equals(other: other.ModificationTimestamp)
                ) && 
                (
                    CreationUser == other.CreationUser ||
                    CreationUser != null &&
                    CreationUser.Equals(other: other.CreationUser)
                ) && 
                (
                    ModificationUser == other.ModificationUser ||
                    ModificationUser != null &&
                    ModificationUser.Equals(other: other.ModificationUser)
                ) && 
                (
                    IsActive == other.IsActive ||
                    IsActive != null &&
                    IsActive.Equals(other: other.IsActive)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CodigoPostal != null)
                    hashCode = hashCode * 59 + CodigoPostal.GetHashCode();
                    if (Pais != null)
                    hashCode = hashCode * 59 + Pais.GetHashCode();
                    if (Estado != null)
                    hashCode = hashCode * 59 + Estado.GetHashCode();
                    if (Municipio != null)
                    hashCode = hashCode * 59 + Municipio.GetHashCode();
                    if (Colonia != null)
                    hashCode = hashCode * 59 + Colonia.GetHashCode();
                    if (Calle != null)
                    hashCode = hashCode * 59 + Calle.GetHashCode();
                    if (NumeroExterior != null)
                    hashCode = hashCode * 59 + NumeroExterior.GetHashCode();
                    if (NumeroInterior != null)
                    hashCode = hashCode * 59 + NumeroInterior.GetHashCode();
                    if (Referencia != null)
                    hashCode = hashCode * 59 + Referencia.GetHashCode();
                    if (Guid != null)
                    hashCode = hashCode * 59 + Guid.GetHashCode();
                    if (CreationTimestamp != null)
                    hashCode = hashCode * 59 + CreationTimestamp.GetHashCode();
                    if (ModificationTimestamp != null)
                    hashCode = hashCode * 59 + ModificationTimestamp.GetHashCode();
                    if (CreationUser != null)
                    hashCode = hashCode * 59 + CreationUser.GetHashCode();
                    if (ModificationUser != null)
                    hashCode = hashCode * 59 + ModificationUser.GetHashCode();
                    if (IsActive != null)
                    hashCode = hashCode * 59 + IsActive.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DireccionResult left, DireccionResult right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(DireccionResult left, DireccionResult right)
        {
            return !Equals(objA: left, objB: right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
