/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para guardar el dispositivo movil autorizado
    /// </summary>
    [DataContract]
    public partial class DispositivoMovilAutorizadoRequest : IEquatable<DispositivoMovilAutorizadoRequest>
    { 
        /// <summary>
        /// Gets or Sets Token
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="token")]
        public string Token { get; set; }

        /// <summary>
        /// Gets or Sets IdDispositivo
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="idDispositivo")]
        public string IdDispositivo { get; set; }

        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets Caracteristicas
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="caracteristicas")]
        public string Caracteristicas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DispositivoMovilAutorizadoRequest {\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  IdDispositivo: ").Append(IdDispositivo).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Caracteristicas: ").Append(Caracteristicas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DispositivoMovilAutorizadoRequest)obj);
        }

        /// <summary>
        /// Returns true if DispositivoMovilAutorizadoRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of DispositivoMovilAutorizadoRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DispositivoMovilAutorizadoRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Token == other.Token ||
                    Token != null &&
                    Token.Equals(other.Token)
                ) && 
                (
                    IdDispositivo == other.IdDispositivo ||
                    IdDispositivo != null &&
                    IdDispositivo.Equals(other.IdDispositivo)
                ) && 
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                ) && 
                (
                    Caracteristicas == other.Caracteristicas ||
                    Caracteristicas != null &&
                    Caracteristicas.Equals(other.Caracteristicas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Token != null)
                    hashCode = hashCode * 59 + Token.GetHashCode();
                    if (IdDispositivo != null)
                    hashCode = hashCode * 59 + IdDispositivo.GetHashCode();
                    if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                    if (Caracteristicas != null)
                    hashCode = hashCode * 59 + Caracteristicas.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DispositivoMovilAutorizadoRequest left, DispositivoMovilAutorizadoRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DispositivoMovilAutorizadoRequest left, DispositivoMovilAutorizadoRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
