/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
  
          /// <summary>
          /// Estructura enum para genero
          /// </summary>
          /// <value>Estructura enum para genero</value>
          [JsonConverter(converterType: typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
          public enum GeneroEnum
          {
              /// <summary>
              /// Enum MasculinoEnum for Masculino
              /// </summary>
              [EnumMember(Value = "Masculino")]
              Masculino = 0,
              /// <summary>
              /// Enum FemeninoEnum for Femenino
              /// </summary>
              [EnumMember(Value = "Femenino")]
              Femenino = 1,
              /// <summary>
              /// Enum NoBinarioEnum for NoBinario
              /// </summary>
              [EnumMember(Value = "NoBinario")]
              NoBinario = 2          }
}
