/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para crear/actualizar producto de proveedor
    /// </summary>
    [DataContract]
    public partial class ProductoRequest : IEquatable<ProductoRequest>
    { 
        /// <summary>
        /// Gets or Sets Sku
        /// </summary>
        [Required]

        [MaxLength(50)]
        [DataMember(Name="sku")]
        public string Sku { get; set; }

        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [Required]

        [MaxLength(100)]
        [DataMember(Name="nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets Precio
        /// </summary>

        [DataMember(Name="precio")]
        public decimal? Precio { get; set; }

        /// <summary>
        /// Gets or Sets UrlIcono
        /// </summary>
        [Required]

        [MaxLength(255)]
        [DataMember(Name="urlIcono")]
        public string UrlIcono { get; set; }

        /// <summary>
        /// Gets or Sets Categoria
        /// </summary>
        [Required]

        [DataMember(Name="categoria")]
        public CategoriaEnum Categoria { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductoRequest {\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Precio: ").Append(Precio).Append("\n");
            sb.Append("  UrlIcono: ").Append(UrlIcono).Append("\n");
            sb.Append("  Categoria: ").Append(Categoria).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductoRequest)obj);
        }

        /// <summary>
        /// Returns true if ProductoRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductoRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductoRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Sku == other.Sku ||
                    Sku != null &&
                    Sku.Equals(other.Sku)
                ) && 
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                ) && 
                (
                    Precio == other.Precio ||
                    Precio != null &&
                    Precio.Equals(other.Precio)
                ) && 
                (
                    UrlIcono == other.UrlIcono ||
                    UrlIcono != null &&
                    UrlIcono.Equals(other.UrlIcono)
                ) && 
                (
                    Categoria == other.Categoria ||
                    Categoria != null &&
                    Categoria.Equals(other.Categoria)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Sku != null)
                    hashCode = hashCode * 59 + Sku.GetHashCode();
                    if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                    if (Precio != null)
                    hashCode = hashCode * 59 + Precio.GetHashCode();
                    if (UrlIcono != null)
                    hashCode = hashCode * 59 + UrlIcono.GetHashCode();
                    if (Categoria != null)
                    hashCode = hashCode * 59 + Categoria.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductoRequest left, ProductoRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductoRequest left, ProductoRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
