/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para crear/actualizar proveedor de servicio
    /// </summary>
    [DataContract]
    public partial class ProveedorUpdateRequest : IEquatable<ProveedorUpdateRequest>
    {
        /// <summary>
        /// Gets or Sets BrokerId
        /// </summary>
        [Required]
        [DataMember(Name = "brokerId")]
        public int? BrokerId { get; set; }

        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [Required]
        [StringLength(100, MinimumLength = 1)]
        [DataMember(Name = "nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets UrlIcono
        /// </summary>

        [MaxLength(500)]
        [DataMember(Name = "urlIcono")]
        public string UrlIcono { get; set; }

        /// <summary>
        /// Gets or Sets ConcurrencyToken
        /// </summary>
        [Required]
        [DataMember(Name = "concurrencyToken")]
        public string ConcurrencyToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProveedorUpdateRequest {\n");
            sb.Append("  BrokerId: ").Append(BrokerId).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  UrlIcono: ").Append(UrlIcono).Append("\n");
            sb.Append("  ConcurrencyToken: ").Append(ConcurrencyToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProveedorUpdateRequest)obj);
        }

        /// <summary>
        /// Returns true if ProveedorUpdateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ProveedorUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProveedorUpdateRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    BrokerId == other.BrokerId ||
                    BrokerId != null &&
                    BrokerId.Equals(other.BrokerId)
                ) &&
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                ) &&
                (
                    UrlIcono == other.UrlIcono ||
                    UrlIcono != null &&
                    UrlIcono.Equals(other.UrlIcono)
                ) &&
                (
                    ConcurrencyToken == other.ConcurrencyToken ||
                    ConcurrencyToken != null &&
                    ConcurrencyToken.Equals(other.ConcurrencyToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (BrokerId != null)
                    hashCode = hashCode * 59 + BrokerId.GetHashCode();
                if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                if (UrlIcono != null)
                    hashCode = hashCode * 59 + UrlIcono.GetHashCode();
                if (ConcurrencyToken != null)
                    hashCode = hashCode * 59 + ConcurrencyToken.GetHashCode();
                return hashCode;
            }
        }

        #region Operators

#pragma warning disable 1591

        public static bool operator ==(ProveedorUpdateRequest left, ProveedorUpdateRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProveedorUpdateRequest left, ProveedorUpdateRequest right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591

        #endregion Operators
    }
}
