/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para actualizar servicio favorito
    /// </summary>
    [DataContract]
    public partial class ServicioFavoritoUpdateRequest : IEquatable<ServicioFavoritoUpdateRequest>
    { 
        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [Required]

        [MaxLength(length: 100)]
        [DataMember(Name="alias")]
        public string Alias { get; set; }

        /// <summary>
        /// Gets or Sets NumeroReferencia
        /// </summary>
        [Required]

        [MaxLength(length: 50)]
        [DataMember(Name="numeroReferencia")]
        public string NumeroReferencia { get; set; }

        /// <summary>
        /// Token de concurrencia
        /// </summary>
        /// <value>Token de concurrencia</value>
        [Required]

        [DataMember(Name="concurrencyToken")]
        public string ConcurrencyToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append(value: "class ServicioFavoritoUpdateRequest {\n");
            sb.Append(value: "  Alias: ").Append(value: Alias).Append(value: "\n");
            sb.Append(value: "  NumeroReferencia: ").Append(value: NumeroReferencia).Append(value: "\n");
            sb.Append(value: "  ConcurrencyToken: ").Append(value: ConcurrencyToken).Append(value: "\n");
            sb.Append(value: "}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(value: this, formatting: Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(objA: null, objB: obj)) return false;
            if (ReferenceEquals(objA: this, objB: obj)) return true;
            return obj.GetType() == GetType() && Equals(other: (ServicioFavoritoUpdateRequest)obj);
        }

        /// <summary>
        /// Returns true if ServicioFavoritoUpdateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ServicioFavoritoUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServicioFavoritoUpdateRequest other)
        {
            if (ReferenceEquals(objA: null, objB: other)) return false;
            if (ReferenceEquals(objA: this, objB: other)) return true;

            return 
                (
                    Alias == other.Alias ||
                    Alias != null &&
                    Alias.Equals(value: other.Alias)
                ) && 
                (
                    NumeroReferencia == other.NumeroReferencia ||
                    NumeroReferencia != null &&
                    NumeroReferencia.Equals(value: other.NumeroReferencia)
                ) && 
                (
                    ConcurrencyToken == other.ConcurrencyToken ||
                    ConcurrencyToken != null &&
                    ConcurrencyToken.Equals(value: other.ConcurrencyToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Alias != null)
                    hashCode = hashCode * 59 + Alias.GetHashCode();
                    if (NumeroReferencia != null)
                    hashCode = hashCode * 59 + NumeroReferencia.GetHashCode();
                    if (ConcurrencyToken != null)
                    hashCode = hashCode * 59 + ConcurrencyToken.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ServicioFavoritoUpdateRequest left, ServicioFavoritoUpdateRequest right)
        {
            return Equals(objA: left, objB: right);
        }

        public static bool operator !=(ServicioFavoritoUpdateRequest left, ServicioFavoritoUpdateRequest right)
        {
            return !Equals(objA: left, objB: right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
