/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class TarjetaEmitidaResult : IEquatable<TarjetaEmitidaResult>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>

        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets PanEnmascarado
        /// </summary>

        [DataMember(Name="panEnmascarado")]
        public string PanEnmascarado { get; set; }

        /// <summary>
        /// Gets or Sets FechaExpiracion
        /// </summary>

        [DataMember(Name="fechaExpiracion")]
        public DateTime? FechaExpiracion { get; set; }

        /// <summary>
        /// Gets or Sets Estado
        /// </summary>

        [DataMember(Name="estado")]
        public EstadoTarjetaEnum Estado { get; set; }

        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>

        [DataMember(Name="tipo")]
        public TipoTarjetaEnum Tipo { get; set; }

        /// <summary>
        /// Gets or Sets LimiteDiario
        /// </summary>

        [DataMember(Name="limiteDiario")]
        public decimal? LimiteDiario { get; set; }

        /// <summary>
        /// Gets or Sets ComprasEnLineaHabilitadas
        /// </summary>

        [DataMember(Name="comprasEnLineaHabilitadas")]
        public bool? ComprasEnLineaHabilitadas { get; set; }

        /// <summary>
        /// Gets or Sets RetirosCajeroHabilitados
        /// </summary>

        [DataMember(Name="retirosCajeroHabilitados")]
        public bool? RetirosCajeroHabilitados { get; set; }

        /// <summary>
        /// Gets or Sets NombreImpreso
        /// </summary>

        [DataMember(Name="nombreImpreso")]
        public string NombreImpreso { get; set; }

        /// <summary>
        /// Gets or Sets EstadoEntrega
        /// </summary>

        [DataMember(Name="estadoEntrega")]
        public EstadoEntregaEnum EstadoEntrega { get; set; }

        /// <summary>
        /// Guid unico del registro
        /// </summary>
        /// <value>Guid unico del registro</value>
        [Required]

        [DataMember(Name="guid")]
        public Guid? Guid { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        /// <value>Creation timestamp</value>
        [Required]

        [DataMember(Name="creationTimestamp")]
        public DateTime? CreationTimestamp { get; set; }

        /// <summary>
        /// Modification timestamp
        /// </summary>
        /// <value>Modification timestamp</value>
        [Required]

        [DataMember(Name="modificationTimestamp")]
        public DateTime? ModificationTimestamp { get; set; }

        /// <summary>
        /// Guid of the creation user
        /// </summary>
        /// <value>Guid of the creation user</value>
        [Required]

        [DataMember(Name="creationUser")]
        public Guid? CreationUser { get; set; }

        /// <summary>
        /// Guid of the modification user
        /// </summary>
        /// <value>Guid of the modification user</value>
        [Required]

        [DataMember(Name="modificationUser")]
        public Guid? ModificationUser { get; set; }

        /// <summary>
        /// Guid of the modification user
        /// </summary>
        /// <value>Guid of the modification user</value>
        [Required]

        [DataMember(Name="isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Token de concurrencia
        /// </summary>
        /// <value>Token de concurrencia</value>
        [Required]

        [DataMember(Name="concurrencyToken")]
        public string ConcurrencyToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TarjetaEmitidaResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PanEnmascarado: ").Append(PanEnmascarado).Append("\n");
            sb.Append("  FechaExpiracion: ").Append(FechaExpiracion).Append("\n");
            sb.Append("  Estado: ").Append(Estado).Append("\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("  LimiteDiario: ").Append(LimiteDiario).Append("\n");
            sb.Append("  ComprasEnLineaHabilitadas: ").Append(ComprasEnLineaHabilitadas).Append("\n");
            sb.Append("  RetirosCajeroHabilitados: ").Append(RetirosCajeroHabilitados).Append("\n");
            sb.Append("  NombreImpreso: ").Append(NombreImpreso).Append("\n");
            sb.Append("  EstadoEntrega: ").Append(EstadoEntrega).Append("\n");
            sb.Append("  Guid: ").Append(Guid).Append("\n");
            sb.Append("  CreationTimestamp: ").Append(CreationTimestamp).Append("\n");
            sb.Append("  ModificationTimestamp: ").Append(ModificationTimestamp).Append("\n");
            sb.Append("  CreationUser: ").Append(CreationUser).Append("\n");
            sb.Append("  ModificationUser: ").Append(ModificationUser).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ConcurrencyToken: ").Append(ConcurrencyToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TarjetaEmitidaResult)obj);
        }

        /// <summary>
        /// Returns true if TarjetaEmitidaResult instances are equal
        /// </summary>
        /// <param name="other">Instance of TarjetaEmitidaResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TarjetaEmitidaResult other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    PanEnmascarado == other.PanEnmascarado ||
                    PanEnmascarado != null &&
                    PanEnmascarado.Equals(other.PanEnmascarado)
                ) && 
                (
                    FechaExpiracion == other.FechaExpiracion ||
                    FechaExpiracion != null &&
                    FechaExpiracion.Equals(other.FechaExpiracion)
                ) && 
                (
                    Estado == other.Estado ||
                    Estado != null &&
                    Estado.Equals(other.Estado)
                ) && 
                (
                    Tipo == other.Tipo ||
                    Tipo != null &&
                    Tipo.Equals(other.Tipo)
                ) && 
                (
                    LimiteDiario == other.LimiteDiario ||
                    LimiteDiario != null &&
                    LimiteDiario.Equals(other.LimiteDiario)
                ) && 
                (
                    ComprasEnLineaHabilitadas == other.ComprasEnLineaHabilitadas ||
                    ComprasEnLineaHabilitadas != null &&
                    ComprasEnLineaHabilitadas.Equals(other.ComprasEnLineaHabilitadas)
                ) && 
                (
                    RetirosCajeroHabilitados == other.RetirosCajeroHabilitados ||
                    RetirosCajeroHabilitados != null &&
                    RetirosCajeroHabilitados.Equals(other.RetirosCajeroHabilitados)
                ) && 
                (
                    NombreImpreso == other.NombreImpreso ||
                    NombreImpreso != null &&
                    NombreImpreso.Equals(other.NombreImpreso)
                ) && 
                (
                    EstadoEntrega == other.EstadoEntrega ||
                    EstadoEntrega != null &&
                    EstadoEntrega.Equals(other.EstadoEntrega)
                ) && 
                (
                    Guid == other.Guid ||
                    Guid != null &&
                    Guid.Equals(other.Guid)
                ) && 
                (
                    CreationTimestamp == other.CreationTimestamp ||
                    CreationTimestamp != null &&
                    CreationTimestamp.Equals(other.CreationTimestamp)
                ) && 
                (
                    ModificationTimestamp == other.ModificationTimestamp ||
                    ModificationTimestamp != null &&
                    ModificationTimestamp.Equals(other.ModificationTimestamp)
                ) && 
                (
                    CreationUser == other.CreationUser ||
                    CreationUser != null &&
                    CreationUser.Equals(other.CreationUser)
                ) && 
                (
                    ModificationUser == other.ModificationUser ||
                    ModificationUser != null &&
                    ModificationUser.Equals(other.ModificationUser)
                ) && 
                (
                    IsActive == other.IsActive ||
                    IsActive != null &&
                    IsActive.Equals(other.IsActive)
                ) && 
                (
                    ConcurrencyToken == other.ConcurrencyToken ||
                    ConcurrencyToken != null &&
                    ConcurrencyToken.Equals(other.ConcurrencyToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (PanEnmascarado != null)
                    hashCode = hashCode * 59 + PanEnmascarado.GetHashCode();
                    if (FechaExpiracion != null)
                    hashCode = hashCode * 59 + FechaExpiracion.GetHashCode();
                    if (Estado != null)
                    hashCode = hashCode * 59 + Estado.GetHashCode();
                    if (Tipo != null)
                    hashCode = hashCode * 59 + Tipo.GetHashCode();
                    if (LimiteDiario != null)
                    hashCode = hashCode * 59 + LimiteDiario.GetHashCode();
                    if (ComprasEnLineaHabilitadas != null)
                    hashCode = hashCode * 59 + ComprasEnLineaHabilitadas.GetHashCode();
                    if (RetirosCajeroHabilitados != null)
                    hashCode = hashCode * 59 + RetirosCajeroHabilitados.GetHashCode();
                    if (NombreImpreso != null)
                    hashCode = hashCode * 59 + NombreImpreso.GetHashCode();
                    if (EstadoEntrega != null)
                    hashCode = hashCode * 59 + EstadoEntrega.GetHashCode();
                    if (Guid != null)
                    hashCode = hashCode * 59 + Guid.GetHashCode();
                    if (CreationTimestamp != null)
                    hashCode = hashCode * 59 + CreationTimestamp.GetHashCode();
                    if (ModificationTimestamp != null)
                    hashCode = hashCode * 59 + ModificationTimestamp.GetHashCode();
                    if (CreationUser != null)
                    hashCode = hashCode * 59 + CreationUser.GetHashCode();
                    if (ModificationUser != null)
                    hashCode = hashCode * 59 + ModificationUser.GetHashCode();
                    if (IsActive != null)
                    hashCode = hashCode * 59 + IsActive.GetHashCode();
                    if (ConcurrencyToken != null)
                    hashCode = hashCode * 59 + ConcurrencyToken.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TarjetaEmitidaResult left, TarjetaEmitidaResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TarjetaEmitidaResult left, TarjetaEmitidaResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
