/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Wallet.RestAPI.Helpers;

namespace Wallet.RestAPI.Models
{
  
          /// <summary>
          /// Gets or Sets TipoTarjetaEnum
          /// </summary>
          [JsonConverter(converterType: typeof(CustomStringToEnumConverter<TipoTarjetaEnum>))]
          public enum TipoTarjetaEnum
          {
              /// <summary>
              /// Enum FisicaEnum for Fisica
              /// </summary>
              [EnumMember(Value = "Fisica")]
              FisicaEnum = 0,
              /// <summary>
              /// Enum VirtualEnum for Virtual
              /// </summary>
              [EnumMember(Value = "Virtual")]
              VirtualEnum = 1          }
}
