/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para guardar la ubicacion o geolocalizacion
    /// </summary>
    [DataContract]
    public partial class UbicacionRequest : IEquatable<UbicacionRequest>
    { 
        /// <summary>
        /// Gets or Sets Latitud
        /// </summary>
        [Required]

        [DataMember(Name="latitud")]
        public decimal? Latitud { get; set; }

        /// <summary>
        /// Gets or Sets Longitud
        /// </summary>
        [Required]

        [DataMember(Name="longitud")]
        public decimal? Longitud { get; set; }

        /// <summary>
        /// Gets or Sets Dispositivo
        /// </summary>
        [Required]

        [DataMember(Name="Dispositivo")]
        public DispositivoEnum Dispositivo { get; set; }

        /// <summary>
        /// Gets or Sets TipoEvento
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="TipoEvento")]
        public string TipoEvento { get; set; }

        /// <summary>
        /// Gets or Sets TipoDispositivo
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="TipoDispositivo")]
        public string TipoDispositivo { get; set; }

        /// <summary>
        /// Gets or Sets Agente
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="Agente")]
        public string Agente { get; set; }

        /// <summary>
        /// Gets or Sets DireccionIP
        /// </summary>
        [Required]

        [StringLength(45, MinimumLength=1)]
        [DataMember(Name="DireccionIP")]
        public string DireccionIP { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UbicacionRequest {\n");
            sb.Append("  Latitud: ").Append(Latitud).Append("\n");
            sb.Append("  Longitud: ").Append(Longitud).Append("\n");
            sb.Append("  Dispositivo: ").Append(Dispositivo).Append("\n");
            sb.Append("  TipoEvento: ").Append(TipoEvento).Append("\n");
            sb.Append("  TipoDispositivo: ").Append(TipoDispositivo).Append("\n");
            sb.Append("  Agente: ").Append(Agente).Append("\n");
            sb.Append("  DireccionIP: ").Append(DireccionIP).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UbicacionRequest)obj);
        }

        /// <summary>
        /// Returns true if UbicacionRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UbicacionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UbicacionRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Latitud == other.Latitud ||
                    Latitud != null &&
                    Latitud.Equals(other.Latitud)
                ) && 
                (
                    Longitud == other.Longitud ||
                    Longitud != null &&
                    Longitud.Equals(other.Longitud)
                ) && 
                (
                    Dispositivo == other.Dispositivo ||
                    Dispositivo != null &&
                    Dispositivo.Equals(other.Dispositivo)
                ) && 
                (
                    TipoEvento == other.TipoEvento ||
                    TipoEvento != null &&
                    TipoEvento.Equals(other.TipoEvento)
                ) && 
                (
                    TipoDispositivo == other.TipoDispositivo ||
                    TipoDispositivo != null &&
                    TipoDispositivo.Equals(other.TipoDispositivo)
                ) && 
                (
                    Agente == other.Agente ||
                    Agente != null &&
                    Agente.Equals(other.Agente)
                ) && 
                (
                    DireccionIP == other.DireccionIP ||
                    DireccionIP != null &&
                    DireccionIP.Equals(other.DireccionIP)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Latitud != null)
                    hashCode = hashCode * 59 + Latitud.GetHashCode();
                    if (Longitud != null)
                    hashCode = hashCode * 59 + Longitud.GetHashCode();
                    if (Dispositivo != null)
                    hashCode = hashCode * 59 + Dispositivo.GetHashCode();
                    if (TipoEvento != null)
                    hashCode = hashCode * 59 + TipoEvento.GetHashCode();
                    if (TipoDispositivo != null)
                    hashCode = hashCode * 59 + TipoDispositivo.GetHashCode();
                    if (Agente != null)
                    hashCode = hashCode * 59 + Agente.GetHashCode();
                    if (DireccionIP != null)
                    hashCode = hashCode * 59 + DireccionIP.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UbicacionRequest left, UbicacionRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UbicacionRequest left, UbicacionRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
