/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// Estructura para consultar usuarios
    /// </summary>
    [DataContract]
    public partial class UsuarioResult : IEquatable<UsuarioResult>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]

        [DataMember(Name="id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets CodigoPais
        /// </summary>
        [Required]

        [DataMember(Name="codigoPais")]
        public string CodigoPais { get; set; }

        /// <summary>
        /// Gets or Sets Telefono
        /// </summary>
        [Required]

        [DataMember(Name="telefono")]
        public string Telefono { get; set; }

        /// <summary>
        /// Gets or Sets CorreoElectronico
        /// </summary>

        [DataMember(Name="correoElectronico")]
        public string CorreoElectronico { get; set; }

        /// <summary>
        /// Gets or Sets Estatus
        /// </summary>
        [Required]

        [DataMember(Name="estatus")]
        public string Estatus { get; set; }

        /// <summary>
        /// Gets or Sets CreationUser
        /// </summary>
        [Required]

        [DataMember(Name="creationUser")]
        public Guid? CreationUser { get; set; }

        /// <summary>
        /// Gets or Sets ModificationUser
        /// </summary>
        [Required]

        [DataMember(Name="modificationUser")]
        public Guid? ModificationUser { get; set; }

        /// <summary>
        /// Gets or Sets CreationTimestamp
        /// </summary>
        [Required]

        [DataMember(Name="creationTimestamp")]
        public DateTime? CreationTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets ModificationTimestamp
        /// </summary>
        [Required]

        [DataMember(Name="modificationTimestamp")]
        public DateTime? ModificationTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [Required]

        [DataMember(Name="isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Token de concurrencia
        /// </summary>
        /// <value>Token de concurrencia</value>

        [DataMember(Name="concurrencyToken")]
        public string ConcurrencyToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UsuarioResult {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CodigoPais: ").Append(CodigoPais).Append("\n");
            sb.Append("  Telefono: ").Append(Telefono).Append("\n");
            sb.Append("  CorreoElectronico: ").Append(CorreoElectronico).Append("\n");
            sb.Append("  Estatus: ").Append(Estatus).Append("\n");
            sb.Append("  CreationUser: ").Append(CreationUser).Append("\n");
            sb.Append("  ModificationUser: ").Append(ModificationUser).Append("\n");
            sb.Append("  CreationTimestamp: ").Append(CreationTimestamp).Append("\n");
            sb.Append("  ModificationTimestamp: ").Append(ModificationTimestamp).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  ConcurrencyToken: ").Append(ConcurrencyToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UsuarioResult)obj);
        }

        /// <summary>
        /// Returns true if UsuarioResult instances are equal
        /// </summary>
        /// <param name="other">Instance of UsuarioResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UsuarioResult other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    CodigoPais == other.CodigoPais ||
                    CodigoPais != null &&
                    CodigoPais.Equals(other.CodigoPais)
                ) && 
                (
                    Telefono == other.Telefono ||
                    Telefono != null &&
                    Telefono.Equals(other.Telefono)
                ) && 
                (
                    CorreoElectronico == other.CorreoElectronico ||
                    CorreoElectronico != null &&
                    CorreoElectronico.Equals(other.CorreoElectronico)
                ) && 
                (
                    Estatus == other.Estatus ||
                    Estatus != null &&
                    Estatus.Equals(other.Estatus)
                ) && 
                (
                    CreationUser == other.CreationUser ||
                    CreationUser != null &&
                    CreationUser.Equals(other.CreationUser)
                ) && 
                (
                    ModificationUser == other.ModificationUser ||
                    ModificationUser != null &&
                    ModificationUser.Equals(other.ModificationUser)
                ) && 
                (
                    CreationTimestamp == other.CreationTimestamp ||
                    CreationTimestamp != null &&
                    CreationTimestamp.Equals(other.CreationTimestamp)
                ) && 
                (
                    ModificationTimestamp == other.ModificationTimestamp ||
                    ModificationTimestamp != null &&
                    ModificationTimestamp.Equals(other.ModificationTimestamp)
                ) && 
                (
                    IsActive == other.IsActive ||
                    IsActive != null &&
                    IsActive.Equals(other.IsActive)
                ) && 
                (
                    ConcurrencyToken == other.ConcurrencyToken ||
                    ConcurrencyToken != null &&
                    ConcurrencyToken.Equals(other.ConcurrencyToken)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (CodigoPais != null)
                    hashCode = hashCode * 59 + CodigoPais.GetHashCode();
                    if (Telefono != null)
                    hashCode = hashCode * 59 + Telefono.GetHashCode();
                    if (CorreoElectronico != null)
                    hashCode = hashCode * 59 + CorreoElectronico.GetHashCode();
                    if (Estatus != null)
                    hashCode = hashCode * 59 + Estatus.GetHashCode();
                    if (CreationUser != null)
                    hashCode = hashCode * 59 + CreationUser.GetHashCode();
                    if (ModificationUser != null)
                    hashCode = hashCode * 59 + ModificationUser.GetHashCode();
                    if (CreationTimestamp != null)
                    hashCode = hashCode * 59 + CreationTimestamp.GetHashCode();
                    if (ModificationTimestamp != null)
                    hashCode = hashCode * 59 + ModificationTimestamp.GetHashCode();
                    if (IsActive != null)
                    hashCode = hashCode * 59 + IsActive.GetHashCode();
                    if (ConcurrencyToken != null)
                    hashCode = hashCode * 59 + ConcurrencyToken.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UsuarioResult left, UsuarioResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UsuarioResult left, UsuarioResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
