/*
 * Wallet Service API
 *
 * Api para exponer la funcionalidad de wallet service. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Wallet.RestAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VincularTarjetaRequest : IEquatable<VincularTarjetaRequest>
    { 
        /// <summary>
        /// Gets or Sets NumeroTarjeta
        /// </summary>
        [Required]

        [DataMember(Name="numeroTarjeta")]
        public string NumeroTarjeta { get; set; }

        /// <summary>
        /// Gets or Sets Alias
        /// </summary>
        [Required]

        [DataMember(Name="alias")]
        public string Alias { get; set; }

        /// <summary>
        /// Gets or Sets Marca
        /// </summary>
        [Required]

        [DataMember(Name="marca")]
        public MarcaTarjetaEnum Marca { get; set; }

        /// <summary>
        /// Gets or Sets FechaExpiracion
        /// </summary>
        [Required]

        [DataMember(Name="fechaExpiracion")]
        public DateTime? FechaExpiracion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VincularTarjetaRequest {\n");
            sb.Append("  NumeroTarjeta: ").Append(NumeroTarjeta).Append("\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  Marca: ").Append(Marca).Append("\n");
            sb.Append("  FechaExpiracion: ").Append(FechaExpiracion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VincularTarjetaRequest)obj);
        }

        /// <summary>
        /// Returns true if VincularTarjetaRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of VincularTarjetaRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VincularTarjetaRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    NumeroTarjeta == other.NumeroTarjeta ||
                    NumeroTarjeta != null &&
                    NumeroTarjeta.Equals(other.NumeroTarjeta)
                ) && 
                (
                    Alias == other.Alias ||
                    Alias != null &&
                    Alias.Equals(other.Alias)
                ) && 
                (
                    Marca == other.Marca ||
                    Marca != null &&
                    Marca.Equals(other.Marca)
                ) && 
                (
                    FechaExpiracion == other.FechaExpiracion ||
                    FechaExpiracion != null &&
                    FechaExpiracion.Equals(other.FechaExpiracion)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (NumeroTarjeta != null)
                    hashCode = hashCode * 59 + NumeroTarjeta.GetHashCode();
                    if (Alias != null)
                    hashCode = hashCode * 59 + Alias.GetHashCode();
                    if (Marca != null)
                    hashCode = hashCode * 59 + Marca.GetHashCode();
                    if (FechaExpiracion != null)
                    hashCode = hashCode * 59 + FechaExpiracion.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(VincularTarjetaRequest left, VincularTarjetaRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VincularTarjetaRequest left, VincularTarjetaRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
